version: '3'

services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"

    mysql:
        image: mysql:5.6.40
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    nginx:
        image: nginx:latest
        ports:
            - "8888:80"